Prefix: "&c[&4Gui Shop&c]"
No-Item: "&cYou do not have enough of {item} in your inventory!"
No-Perm: "&c&lYou do not have permission to create a sign!"
No-Perm-Cmd: "&c&lYou do not have permission to execute this command!"
New-Bal: "&6Your new balance is {bal}!"
No-Item-In-Cart: "&6You cannot buy air! Please select items you want to buy!"
No-Money: "&cYou cannot afford the item {item}"
Full-Inventory: "&cYou don't have enough space in your inventory to buy the item!"
Transaction-Cancelled: "&cThe current transaction has been terminated!"
Transaction-Successful: "&cYou have bought the item(s) &6{item} &c!"
Currency-Sign: "$"